### ISSUE TITLE
For closed events, change the button text from register to something else.

### ISSUE THREAD

**Issue by shawshankkumar** [srm-kzilla/srmkzilla-net#55]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/74819565/190554890-5a3d9850-831a-4be4-bbe3-ee4f6405d632.png">

**Comment by flying-solo** [comment]
hello 👋 @shawshankkumar  , can i solve this issue

**Comment by shawshankkumar** [comment]
Hi @flying-solo . Can you give us a rough sketch of how you'd fix this issue?

**Comment by flying-solo** [comment]
i want to know , how u are maintaining the dates for the event if it got over physically

**Comment by shawshankkumar** [comment]
We have a database where we keep track of all the events. We have an API(written in GO) which helps the front end(SSR) fetch data from the database.

**Comment by flying-solo** [comment]
okay cool lemme check it out

**Comment by shawshankkumar** [comment]
Please go through the code once and explain briefly how you would work on this.

**Comment by flying-solo** [comment]
> hey buddy ! can you help me with this error

![image](https://user-images.githubusercontent.com/73738347/191528946-bd4a67bc-910f-45f4-83ea-8e432d27ab1e.png)

**Comment by shawshankkumar** [comment]
Please wrtie `node --version` in the terminal and attach a screenshot.

**Comment by flying-solo** [comment]
> node version is being displayed
![image](https://user-images.githubusercontent.com/73738347/191530186-a27cce4c-6826-4bfd-9d87-8ce69d1e4110.png)

**Comment by flying-solo** [comment]
lo 
![image](https://user-images.githubusercontent.com/73738347/191530598-4d8502ee-f9cf-4cfb-8200-ee3c4b085ed8.png)

**Comment by shawshankkumar** [comment]
Please delete yarn.lock and node_module then install the packages again and then try.

**Comment by flying-solo** [comment]
> Hi @flying-solo . Can you give us a rough sketch of how you'd fix this issue?

i have seen the code and there's a boolean variable eventCompleted ; i will use this to manage the button

**Comment by shawshankkumar** [comment]
@flying-solo Can you try downgrading the node version ? You can use nvm if you wish.

**Comment by shawshankkumar** [comment]
> > Hi @flying-solo . Can you give us a rough sketch of how you'd fix this issue?
> 
> i have seen the code and there's a boolean variable eventCompleted ; i will use this to manage the button

Which files are you planning on changing and what would be the alternative text and button color?

**Comment by flying-solo** [comment]
specify the particular node version

**Comment by shawshankkumar** [comment]
Can you try 16.x.x for this? And report back.

**Comment by flying-solo** [comment]
> > > Hi @flying-solo . Can you give us a rough sketch of how you'd fix this issue?
> > 
> > 
> > i have seen the code and there's a boolean variable eventCompleted ; i will use this to manage the button
> 
> Which files are you planning on changing and what would be the alternative text and button color?

button color would be grey and text would be event ended, 
i will use condtional rendering to check for the boolean value.

**Comment by shawshankkumar** [comment]
Alright. Looks good to me. @agarwalviraj is our Technical lead and we both will be reviewing any and all changes. I am assigning this to you, all the best!

**Comment by flying-solo** [comment]
@shawshankkumar by changing the node version it worked

**Comment by flying-solo** [comment]
> @shawshankkumar by changing the node version it worked

but i am not having the credential for the api call

**Comment by shawshankkumar** [comment]
> > @shawshankkumar by changing the node version it worked
> 
> but i am not having the credential for the api call

Yes. What you can do at the moment is use sample data which we can provide.

**Comment by flying-solo** [comment]
but i guess i can fix this issue without an api call
