### ISSUE TITLE
Create .env.example

### ISSUE THREAD

**Issue by shawshankkumar** [srm-kzilla/srmkzilla-net#56]

**Comment by vaishnav-mk** [comment]
Could I work on this?
I believe the ENVs you use are just `NEXT_PUBLIC_YOUTUBE_KEY= <string: YouTube API key>` , `SANITY_ID=<string: Sanity ID>` and `INSTA_KEY: <string>` along with `NEXT_PUBLIC_BASE_URL` for api calls?

**Comment by CampVamp** [comment]
I will complete it by 2nd January 2023
