### ISSUE TITLE
Instagram followers value is empty for /services

### ISSUE THREAD

**Issue by vaishnav-mk** [srm-kzilla/srmkzilla-net#58]
# Expected Behavior

![image](https://user-images.githubusercontent.com/84540554/194450881-c2942747-6793-4490-be84-3c95c46df0b4.png)

The follower count should be displayed properly

# Current Behavior

![image](https://user-images.githubusercontent.com/84540554/194450927-fe1756e9-ac68-4a20-a232-77a270ca7647.png)

It isn't being displayed properly

Upon examining this [line](https://github.com/srm-kzilla/srmkzilla-net/blob/main/shared/components/services/numbers.tsx#L19) specifically and making the call myself, it's observed that `graphql` isn't really a valid field in the data object that is being returned and it doesn't really raise an [error](https://github.com/srm-kzilla/srmkzilla-net/blob/main/shared/components/services/numbers.tsx#L22) for it reach the catch block and set followers to 2400 so it's basically an empty string which is being displayed.

A potential solution would be to just declare the state with '2400', figure out a different way to fetch the right followers and then update the state,

**Comment by shawshankkumar** [comment]
Hey @vaishnav-mk why dont you submit a pr for this?

**Comment by vaishnav-mk** [comment]
Well, upon closer inspection, I don't think `https://www.instagram.com/srmkzilla/?__a=1` is meant to be used anymore as it either errors out due to cors errors or doesn't return anything important so I'm assuming they either removed it or an average person doesn't have enough perms for it unless I'm wrong as I'm not sure how instagram works behind the scenes.
Some of the other ways that you can use to fetch the count are:
* Using the Instagram Graph API: [The Instagram Graph API](https://developers.facebook.com/docs/instagram-api) allows you to retrieve a list of the followers of an Instagram account. To use the Instagram Graph API, you will need to register your app with Facebook and get an access token.
* Using the Instagram Private API: The Instagram Private API is a proprietary API that is not publicly available, and access to it is restricted to approved partners. If you are an approved partner, you can use the Instagram Private API to fetch the followers of an Instagram account.
* ...or the *other* method where you scrape it off which is most likely unreliable mainly because it sits behind cloudflare

I'm not sure of how I'm supposed to move ahead and that's why I haven't made a pr yet. Do let me know if you have a solution to this!

**Comment by shawshankkumar** [comment]
We were thinking about hard coding it for the time being and then working on a better solution.

**Comment by vaishnav-mk** [comment]
also, fyi, 
your sanity id is [here](https://github.com/srm-kzilla/srmkzilla-net/blob/main/shared/client.ts#L4)
your events api base url is [here](https://github.com/srm-kzilla/zeus-frontend/commit/f7a86b763d314146c15948ec33072dfeaec007ce)
one of your jwt tokens is [here](https://github.com/srm-kzilla/srmkzilla-net/blob/main/utils/api.ts#L7)

for [validating refresh tokens](https://github.com/srm-kzilla/zeus-backend/blob/d3a5c8b3a772a6519b77bed29aad2fa650a84ce7/api/auth/service/authService.go#L49), looks like the function is called during parsing to verify that the jwt is valid. In this case, the validation function simply returns the secret key as the signing key and a nil error, which means that the JWT is considered to be valid. It should probably check the expiration time and the issuer along with verifying the signature

**Comment by shawshankkumar** [comment]
> also, fyi, your sanity id is [here](https://github.com/srm-kzilla/srmkzilla-net/blob/main/shared/client.ts#L4) your events api base url is [here](https://github.com/srm-kzilla/zeus-frontend/commit/f7a86b763d314146c15948ec33072dfeaec007ce) ~one of your jwt tokens is [here](https://github.com/srm-kzilla/srmkzilla-net/blob/main/utils/api.ts#L7) (ah, looks like the token issued to esh expired 7 months ago)~
> 
> for [validating refresh tokens](https://github.com/srm-kzilla/zeus-backend/blob/d3a5c8b3a772a6519b77bed29aad2fa650a84ce7/api/auth/service/authService.go#L49), it looks like the function is called during parsing to verify that the jwt is valid. In this case, the validation function simply returns the secret key as the signing key and a nil error, which means that the JWT is considered to be valid. It should probably check the expiration time and the issuer along with verifying the signature

A member is already working on this. Cheers!
