### ISSUE TITLE
Create Drop Down for Registering.

### ISSUE THREAD

**Issue by agarwalviraj** [srm-kzilla/srmkzilla-net#61]
# Expected Behavior

There should be a drop down called department menu for selecting department in `/register`. The dropdown should have 5 options CINTEL, DSBS, CTECH, NWC and Others.

# Current Behavior

There is no drop down for department now.

## Context

Since we require department for giving OD to students, the drop down is necessary.

**Comment by CampVamp** [comment]
I will complete it by 2nd January 2023
