### ISSUE TITLE
Create Prize Card

### ISSUE THREAD

**Issue by agarwalviraj** [srm-kzilla/srmkzilla-net#62]
# Expected Behavior
Create a prizes component to be displayed on `/events/[slug]` route. The cards will appear according to the number of prizes present in the back end. The prize card can appear after the speaker section.

# Current Behavior
There is no prizes section in the front end right now.

**Comment by shawshankkumar** [comment]
@CampVamp we have shared the schema with you, please refer to that!

**Comment by CampVamp** [comment]
I will complete it by 2nd January 2023
