### ISSUE TITLE
Show even over and disable button for events that are over.

### ISSUE THREAD

**Issue by shawshankkumar** [srm-kzilla/srmkzilla-net#63]
![image](https://user-images.githubusercontent.com/74819565/209837247-dcd2f737-64be-4853-9835-5173158bf36d.png)

Here all three events show Register now. Disable that button and change the text

**Comment by vaishnav-mk** [comment]
isn't that the case now?
![image](https://user-images.githubusercontent.com/84540554/209867608-ec1707db-c460-4c16-865c-ded4ee6b2fef.png)
https://github.com/srm-kzilla/srmkzilla-net/blob/main/shared/components/events/card.tsx#L36
