### ISSUE TITLE
Migrate to Node.js 18.x

### ISSUE THREAD

**Issue by sm-sami** [srm-kzilla/srmkzilla-net#86]
The app must be migrated to Node.js 18.x as Vercel is dropping support for version 14.x Make the necessary changes to `package.json`, and related files. Upgrade the dependencies as well.

![image](https://github.com/srm-kzilla/srmkzilla-net/assets/64266012/76eb648a-ac7c-43bb-a07d-48279cabbade)

**Comment by HarshPatel5940** [comment]
![image](https://github.com/srm-kzilla/srmkzilla-net/assets/83941233/e9faa43c-4788-44b3-9c8e-9ce344c13d70)

Are we expecting to do the above changes with the below engine version change. @sm-sami ?

![image](https://github.com/srm-kzilla/srmkzilla-net/assets/83941233/0845a2ef-f195-49a6-af92-6321b6b65d80)

**Comment by shawshankkumar** [comment]
![image](https://github.com/srm-kzilla/srmkzilla-net/assets/74819565/7c2db99e-9387-4478-97d7-76c19457f98c)
